# Generated by Django 2.2 on 2023-03-19 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='audit.AuditType')),
            ],
        ),
    ]
