# Generated by Django 2.2 on 2023-03-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditcategory',
            old_name='label',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='auditcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='audittype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='audit.AuditType')),
            ],
        ),
    ]
