# Generated by Django 2.2 on 2023-03-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditType',
        ),
    ]
