# Generated by Django 2.2 on 2023-04-11 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditsession',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.AuditType'),
        ),
        migrations.CreateModel(
            name='AuditCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=15)),
                ('audit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.AuditType')),
            ],
        ),
    ]
