# Generated by Django 2.2 on 2023-03-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_delete_audittype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=15)),
            ],
        ),
    ]
